### ISSUE TITLE
Примеры с ObjectManager

### ISSUE THREAD

**Issue by goodok21** [yandex/mapsapi-examples#54]
Здравствуйте! Можете ли Вы добавить пример, где в ObjectManager добавлялись бы объекты с координатами: [65, -178] и coordinates: [65, 178] так, чтобы они смогли образовать кластер и правильно отображаться?

Вот пример того, о чем я говорю: https://codesandbox.io/s/30m5o07wmm
На примере 2 точки на карте, по идее они должны отображаться рядом, но Object Manager не "копирует" точки на другие карты и из-за этого они находятся в разных частях одной карты. Как заставить ObjectManager "скопировать" точки на другие карты или по-другому решить данную проблему?

**Comment by se0ga** [comment]
Я уже вам ответил на SO что это невозможно сделать с OM. Только если не пользоваться OM=)22.07.2018, 13:26, "Alexander Eric" <notifications@github.com>:Здравствуйте! Можете ли Вы добавить пример, где в ObjectManager добавлялись бы объекты с координатами: [65, -178] и coordinates: [65, 178] так, чтобы они смогли образовать кластер и правильно отображаться?
Вот пример того, о чем я говорю: https://codesandbox.io/s/30m5o07wmm
На примере 2 точки на карте, по идее они должны отображаться рядом, но Object Manager не "копирует" точки на другие карты и из-за этого они находятся в разных частях одной карты. Как заставить ObjectManager "скопировать" точки на другие карты или по-другому решить данную проблему?
